### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by ArsenGadjiusmanov** [gunzenroses/hotelPage#1]
Привет 🖐️. Если будут вопросы пиши в тг. 
P.s. Issue надо исправлять по всему проекту и в слайдере тоже.
1. 
![image](https://user-images.githubusercontent.com/89850975/147672450-e6fbb60e-b447-456f-98dc-8456e1db78f4.png)
Каждый компонент должен быть отдельным блоком. Элемент не может существовать вне блока. Если элемент такой большой что хочется его вынести в отельный файл, возможно тогда стоит создать отдельный блок. [тык](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.3) 
2. 
![image](https://user-images.githubusercontent.com/89850975/147673037-428c8f4c-00c3-45b3-ac49-48468551bb78.png)
Именовать [lower-case-hyphenated](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#1.16)
3. 
![image](https://user-images.githubusercontent.com/89850975/147673371-1b44eef0-b461-4972-9f60-540112468ce6.png)
**1 Компонента => 1 Блок**

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/147674540-61f90595-2600-452f-abb1-f2df00cc50db.png)
По БЭМ-у запрещено делать глобальный сброс стилей [тык](https://ru.bem.info/methodology/faq/#%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BD%D0%B5-%D1%81%D1%82%D0%BE%D0%B8%D1%82-%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%BE%D0%B1%D1%89%D0%B8%D0%B9-%D1%81%D0%B1%D1%80%D0%BE%D1%81-%D1%81%D1%82%D0%B8%D0%BB%D0%B5%D0%B9-reset)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/149422522-7a5b262e-e041-4fff-8ccc-e9c69480b59e.png)
1 компонента = 1 блок. Выносить элемента блока нет необходимости. Если тебе нужен отдельный элемент выносишь его в отдельную компоненту.

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/149422917-40144a1d-ea6f-4f49-bc8c-00fc1003c8e9.png)
Модификатор всегда часть блока или элемента нельзя использовать его вне этих сущностей. [БЭМ](https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80-%D0%BD%D0%B5%D0%BB%D1%8C%D0%B7%D1%8F-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%81%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE)

**Comment by gunzenroses** [comment]
>  Выносить элемента блока нет необходимости. Если тебе нужен отдельный элемент выносишь его в отдельную компоненту.

Необходимости нет, но как вариант решения имеет место быть?)
Ориентировалась на файловую структуру по типу [nested](https://ru.bem.info/methodology/filestructure/#nested), согласно которой директория блока выступает корневой для поддиректорий элементов и модификаторов.

**Comment by ArsenGadjiusmanov** [comment]
> 
> Необходимости нет, но как вариант решения имеет место быть?) Ориентировалась на файловую структуру по типу [nested](https://ru.bem.info/methodology/filestructure/#nested), согласно которой директория блока выступает корневой для поддиректорий элементов и модификаторов.

Такую структуру используют из-за css он получается слишком большим если не дробить, но так как мы используем scss в этом нет необходимости

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/152122234-0bab0b45-64d3-4c61-8838-0c8f6187a273.png)
[Имена записываются латиницей в нижнем регистре.](https://ru.bem.info/methodology/naming-convention/#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B8%D0%BC%D0%B5%D0%BD)
