### ISSUE TITLE
переиспользуемость компонентов

### ISSUE THREAD

**Issue by Geksanit** [gunzenroses/hotelPage#17]
![image](https://user-images.githubusercontent.com/31949379/175009573-277856e2-6b04-4321-bfda-d414282b2219.png)
Привет. Компоненты лучше делать переиспользуемыми. Что если понадобится ещё где-то добавить `radioButton` с другими `name/value`?

**Comment by Geksanit** [comment]
к checkbox это тоже относится: список с другими правилами или не правилами а чем угодно.
![image](https://user-images.githubusercontent.com/31949379/175014469-924e2e07-e32d-47f8-8015-ae41e8e44ffb.png)
а ещё тут проблема с именованием, `checkbox -> checkboxList` `checkbox-item -> checkbox` - так ведь сразу понятней что есть что)

**Comment by Geksanit** [comment]
[checkbox-expandable](https://github.com/gunzenroses/hotelPage/tree/a8fd4c85dcb2b930e67a03cfb17bbf28a73a5385/src/components/checkbox-expandable)
тоже

**Comment by gunzenroses** [comment]
Привет! Наконец исправлено!:-)
