### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ArsenGadjiusmanov** [gunzenroses/hotelPage#3]
1. ![image](https://user-images.githubusercontent.com/89850975/147674694-3565c8fa-f15a-4ae6-b21b-356643ee284c.png)
У тебя должен быть один корневой класс блока и уже в нем прописывать стили для его элементов
2. Для медиа выражений удобнее использовать миксины 
![image](https://user-images.githubusercontent.com/89850975/147674995-3475fa78-cd34-46d6-8ec1-ec7f37a0ab43.png)

3.Глобальные стили не допустимы. Допустимы только для тегов body, html и для переопределения box-sizing для всех тегов 
![image](https://user-images.githubusercontent.com/89850975/147675358-b96ee8de-c650-447d-a3df-8640c829d332.png)
Смотри [БП](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.4)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/149423487-6a4eb022-195a-424c-afd9-de77f372b636.png)
Должен быть 1 родительский селектор блока и уже в нем должен располагаться код для элементов, модификаторов и тд. 
Почитай про родительский [селектор](https://sass-lang.com/documentation/style-rules/parent-selector)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/149423824-5abc7c6b-c4c2-40d4-bf96-8697ddac0a1a.png)
Нельзя писать стили одного блока в файле стилей другого. 
maretial-icon в данном случае блок и в badge ему не место

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/149425185-5892ac4b-e447-4851-b5a2-8de151122c34.png)
![image](https://user-images.githubusercontent.com/89850975/149425217-e359f2a2-2467-4a55-a1c5-146a901edd2e.png)
Что это? Зачем это? -____-

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/152123237-20372cb5-aee9-484d-8936-be640003da04.png)
![image](https://user-images.githubusercontent.com/89850975/152124469-38b90386-0bed-4a79-880f-7ef78479dd96.png)

Классы с префиксом js-  используются только для поиска по dom

**Comment by ArsenGadjiusmanov** [comment]
> ![image](https://user-images.githubusercontent.com/89850975/149425185-5892ac4b-e447-4851-b5a2-8de151122c34.png) ![image](https://user-images.githubusercontent.com/89850975/149425217-e359f2a2-2467-4a55-a1c5-146a901edd2e.png) Что это? Зачем это? -____-

Для меня все еще загадка зачем ты создаешь отдельные классы для иконок соц сетей.  Если понадобится добавить еще ссылок с иконками на соц сети понадобиться лезть в код и добавлять новые классы. 
Надо изменить подход. Попробуй применить иконочные шрифты или отдельно сами svg иконки. Ну или еще какой способ на свое усмотрение главное чтоб это было что-то более универсальное

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/152129963-ff6c9486-f716-4b92-a9df-5b52495c78e2.png)
Для префиксов у тебя стоит PostCSS. Зачем ты их в ручную прописываешь ?

**Comment by gunzenroses** [comment]
> Для префиксов у тебя стоит PostCSS. Зачем ты их в ручную прописываешь ?

Стоял postcss-cssnext, который не покрывал некоторые случаи. Обновила пакеты, теперь все в порядке :-)

**Comment by gunzenroses** [comment]
> Для меня все еще загадка зачем ты создаешь отдельные классы для иконок соц сетей

- исправила: для отображения самих иконок использовала дефолтные классы из пакета node (теперь нет проблемы в подключении новых иконок);
- в классах элементов оставила высоту - совсем обойтись не могу, поскольку иконки имеют разную высоту на страницах и единый стиль будет нарушать pixelperfect:-)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153779682-6b0886d1-39e1-4fb0-8dbf-1fbf4372a740.png)
Тут можно использовать синтаксис вложенности и вписать стили прямо в _hover info-sign_

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153780198-6e7a16b1-3462-4ddc-885f-0e76b261d5ba.png)
У тебя в трех местах используется одинаковый код лишь слегка отличающийся. Это там где ты используешь checkbox. Давай вынесем код для checkbox в отдельную компоненту, которая сможет 
Принимать такой вид
![image](https://user-images.githubusercontent.com/89850975/153780290-03590f3b-8c84-4610-80f2-cfd9c703121c.png)
или такой 
![image](https://user-images.githubusercontent.com/89850975/153780301-d99a5d83-3a98-4ca7-b77d-9fc618681440.png)
в зависимости от переданных в нее параметров. А там где нужен этот checkbox мы просто будем использовать эту компоненту и избежим дублирования кода

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153780535-cef0aa41-a824-4b9d-91d2-2cb8fdd2f57c.png)
У тебя написаны стили для модификатора, но нет стилей для самого элемента. Возможно стоит упразднить один из них и сделать его элементом. 

![image](https://user-images.githubusercontent.com/89850975/153780696-3124b457-ceaa-403a-abb6-a2ffd4a9518a.png)
Так же у тебя тут опечатка если ты пользуешь vscode можешь поставить себе плагин [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) p.s. не забудь добавить русский словарь)
