### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by ArsenGadjiusmanov** [gunzenroses/hotelPage#4]
![image](https://user-images.githubusercontent.com/89850975/147675854-8449239a-e4a4-4e1a-9772-9afa81998bab.png)
Файлы экспортирующие класс должны так же носить имя класса который они экспортируют, вместо calendar.js будет Calendar.js и так далее. (PascalCase)

2. Вся бизнес логика компонента должна хранится в классах. Причем класс в файле должен быть один. И называться файл должен точно также как класс. 
![image](https://user-images.githubusercontent.com/89850975/147675922-0f63d428-bd85-4678-97a7-0dd2dad963c3.png)

Каждый класс компоненты должен быть отдельным независимым модулем, который вызывается в файле index.js компоненты либо НазваниеКомпоненты-init.js [Про модульность](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#5.5)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/147676133-781f6971-0671-444d-91f4-e47111a62900.png)
Экспорты необходимо перенести в конец поправь пожалуйста) [тык](https://github.com/fullstack-development/front-end-best-practices/blob/f4139eb680dacb7b35040d0f0b0a2edb6372eb8e/JS/README.md#1.18)

**Comment by gunzenroses** [comment]
> Экспорты необходимо перенести в конец 

1. а это не будет нарушать принцип **dry**?:-) если в файле только один класс (согласно нормативу "1компонент - 1класс"), то не будет ли более логичным экспортировать его по default?

**Comment by gunzenroses** [comment]
> Каждый класс компоненты должен быть отдельным независимым модулем, который вызывается в файле index.js компоненты либо НазваниеКомпоненты-init.js

2.1. То есть предполагаемый функционал должен работать, если сделать _**import component.js**_ в файл соответствующей страницы (например, в landing-page.js'? Если привязка предполагается через имя класса, то тут более-менее понятно, можно заранее создать **instances** в файле **ComponentName-init.js**, а затем уже делать импорт этого файла :-)

2.3. Непонятным остается как быть, если привязка идет через **id**. Например, в ButtonLike классе предполагается, что каждый id связан с определенным количеством лайков **{id: XX, data: YY}** , соответственно создавать инстансы в одном месте, а затем импортировать этот файл на разные страницы будет проблематично (везде ведь будут **разные id, разные data**). Как быть?:-)

**Comment by ArsenGadjiusmanov** [comment]
> > Экспорты необходимо перенести в конец
> 
> 1. а это не будет нарушать принцип **dry**?:-) если в файле только один класс (согласно нормативу "1компонент - 1класс"), то не будет ли более логичным экспортировать его по default?

Да экспорт должен быть по default, но расположить его надо в конце файла.

Долго думал так и не понял, а зачем связывать **id** с количеством лайков? Id следует задавать только для уникальных элементов и если можно обойтись без него, то следует его избегать. Т.е. нельзя чтобы на стр было 2 элемента было с одинаковым id это не валидный код получается. А кнопок может быть сколько угодно на стр. У тебя id используется для для того чтобы навесить обработчик, что мешает сделать тоже самое с классом? И зачем там уникальные значения ?
Надо переделать на классы) [вот еще про id тык](https://github.com/fullstack-development/front-end-best-practices/tree/f4139eb680dacb7b35040d0f0b0a2edb6372eb8e/HTML#2.10)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/149424104-37d0b29a-f496-49e5-aa30-7a2fe6950245.png)
1.Посмотри в сторону данного [пакета](https://www.npmjs.com/package/autobind-decorator), удобная штука для привязки методов к классу. 
2.
![image](https://user-images.githubusercontent.com/89850975/149424540-23cc36b9-4391-4f69-b114-da27ec145bcb.png)
Если передаешь большое количество аргументов(p.s. обычно 3 и более), то лучше передавать их в виде объекта почитай БП там про это написано

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/149425692-efaf63fa-4b3b-4d7a-bbcc-e814bb13a1f7.png)
Тк в паге возможно использование js кода, то нужно придерживаться всех стандартов для js, наших и airbnb.
Если где-то используется js то для него действуют все те же правила что и в обычных js файлах. Pug не является исключением.
А еще лучше если ты это вынесешь в json файл и уже оттуда будешь брать данные для отрисовки

**Comment by gunzenroses** [comment]
![long-params](https://user-images.githubusercontent.com/60935997/150317632-4e4fdcb0-e44b-48ad-975b-858f7dc4e4e6.jpg)

А как можно сократить строку в данном случае?:)

**Comment by ArsenGadjiusmanov** [comment]
> ![long-params](https://user-images.githubusercontent.com/60935997/150317632-4e4fdcb0-e44b-48ad-975b-858f7dc4e4e6.jpg)
> 
> А как можно сократить строку в данном случае?:)

Здесь можешь оставить, так как перенос приводит к ошибке в сборке pug

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/152131732-5205bcf2-2eee-4faf-93c8-54d29356a601.png)
Следует избегать циклов for. Они хуже читаются чем [map/forEach](https://github.com/airbnb/javascript/#iterators--nope)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153779482-703b53cc-8189-4bb3-b919-3544846c5513.png)
Для js по нашим бест практис следует использовать одинарные кавычки. js в pug не является исключением. [тык](https://github.com/airbnb/javascript#strings--quotes)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153780963-6a9bca3a-af4d-421c-b3b8-e91469987184.png)
Все ресурсы должны по максимуму кэшироваться. Ты ищешь элемент через querySelector если он есть то ты еще раз его ищешь  это _не самая дешевая операция_  
p.s. Зачем это не понятно querySelector сам вернет null если ничего не найдено

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153781397-255c6fc7-d069-420d-b743-a8450ac319ec.png)
Для добавления стилей надо использовать классы+css. В js писать стили не нужно

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153781647-fc885309-178f-4f47-82fb-0de76acc2d95.png)
Если переменную дальше нигде не используешь то можно ее не создавать, а просто продолжить цепочку вызовов. _В данном случае ты ее создаешь только для вызова метода на ней._
![image](https://user-images.githubusercontent.com/89850975/153781766-64c6fcc3-8266-49c6-9b85-ca892e5b4432.png)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153782272-57648104-9969-4716-9194-ec7b9ff2f983.png)
![image](https://user-images.githubusercontent.com/89850975/153782286-26b3d5e5-77cc-4e9f-a9db-c6fbadf394c5.png)
Названия классов лучше хранить в переменных
