### ISSUE TITLE
Недочеты сайта

### ISSUE THREAD

**Issue by ArsenGadjiusmanov** [gunzenroses/hotelPage#6]
![image](https://user-images.githubusercontent.com/89850975/147676781-a6289ce3-1272-4ca5-8186-30803d718710.png)
Приятно конечншН) но лучше добавить навигацию по стр чтоб было удобнее просматривать(=^_^=)))

1.  Цвет не соответствует макету  
![image](https://user-images.githubusercontent.com/89850975/147677315-fa3a082e-c0ca-4614-a1e4-a74175de7631.png)

2. Кнопка должна быть кликабельной 
![image](https://user-images.githubusercontent.com/89850975/147677504-e9b2ad4c-d1a9-48d7-85fe-c54b6f7384e3.png)

3. ![image](https://user-images.githubusercontent.com/89850975/147677630-0ca010e6-f413-4f5d-8045-15e80c4e3114.png)
Чекбокс листы лучше не закрывать по клику вне блока 
4. 
![image](https://user-images.githubusercontent.com/89850975/147677765-dd91b41d-b2f0-46cc-9d30-830e62682aa5.png)
 
Клик на пустое пространство переключает кнопку.
p.s. Анимацию на кнопке лучше ускорить
![image](https://user-images.githubusercontent.com/89850975/147677826-0914f009-c71a-4e76-a348-f2d648c62e2c.png)

5. Дергается навигация при hover
https://user-images.githubusercontent.com/89850975/147678542-9a11d147-60a9-410a-9d9d-666f3d41fecb.mp4

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/152134925-f0b31827-514d-4145-a865-7848e83906cd.png)
т.к. больше 10 выставить нельзя, то надо и визуально как-то обозначить что они не активны

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/152135181-4ec6db52-eb59-4c62-8952-1d8e6fe55c8f.png)
Должна быть выплывающая подсказка при наведении на i

**Comment by ArsenGadjiusmanov** [comment]
https://user-images.githubusercontent.com/89850975/152135689-62e36752-c703-46d4-ac68-1d923da07452.mp4

Указатель не переносится при первом заполнении текстом по клику мышки

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/152137046-51fab4cb-ced7-45c2-b4de-2d752f52478d.png)
По макету на кружках есть тень

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/152137488-889a3a11-953e-45df-be3c-2c9a1e3801c6.png)
PP

**Comment by ArsenGadjiusmanov** [comment]
Диаграмма должна быть интерактивное. Сейчас у тебя просто статичная верстка. 
Вот пример https://user-images.githubusercontent.com/89850975/152139013-e1a2c6ea-6798-48d8-a4f5-21d876a5ea9c.mp4
 но ты можешь сделать по своему как это видишь. Главное чтоб значения менялись.
 Реализация на твое усмотрение

**Comment by gunzenroses** [comment]
> ![image](https://user-images.githubusercontent.com/89850975/152137488-889a3a11-953e-45df-be3c-2c9a1e3801c6.png) PP

Проверила по PP в Chrome, Firefox, Edge - везде совпадает. 
![PP](https://user-images.githubusercontent.com/60935997/152551463-ecdd251c-b1fd-4030-b692-4f04b025dc46.jpg)

Это в Safari получается?

**Comment by ArsenGadjiusmanov** [comment]
> > ![image](https://user-images.githubusercontent.com/89850975/152137488-889a3a11-953e-45df-be3c-2c9a1e3801c6.png) PP
> 
> Проверила по PP в Chrome, Firefox, Edge - везде совпадает. ![PP](https://user-images.githubusercontent.com/60935997/152551463-ecdd251c-b1fd-4030-b692-4f04b025dc46.jpg)
> 
> Это в Safari получается?

Это в хроме. Ок если у тебя все совпадает. А размер viewport 1440*900 ?

**Comment by gunzenroses** [comment]
> Это в хроме. Ок если у тебя все совпадает. А размер viewport 1440*900 ?

Да, viewport width 1440 при любой высоте.

**Comment by ArsenGadjiusmanov** [comment]
После достижения определенной ширины (можно прокликать в фигме) footer должен меняться на тот, что нарисован в макете под мобилку. 
![image](https://user-images.githubusercontent.com/89850975/153778128-0b12b98f-92f7-4c08-a34b-671da2cf72ba.png)

**Comment by ArsenGadjiusmanov** [comment]
https://user-images.githubusercontent.com/89850975/153778324-a1ab5828-71af-44bd-b149-7a00cd39a2d6.mp4

1. Карточка для брони при малом вьюпорте начинает перекрывать изображения. 
2. Изображения искажаются при изменении вьюпорта

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153778637-814ec9ab-3d8a-441a-9a76-3fc4e9f834ef.png)
1. Все интерактивный элементы должны обладать свойством **cursor: pointer**  [БП](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#2.9)
2. Кнопка меню бургер не работает на мобильных устройствах поправь пожалуйста

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153778900-7013db1a-7233-4c48-b291-2dbe12c72cb7.png)
Иконка деформируется

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153778957-b4c16888-b02f-484d-8bdc-ae40de19f425.png)
Dropdown должны схлопываться по клику вне элемента

**Comment by ArsenGadjiusmanov** [comment]
https://user-images.githubusercontent.com/89850975/153779130-c8ff39ed-5e34-43c4-8502-fc4d0342372c.mp4

После 1920px стека с карточками  почему-то сбрасывается до 1440px

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/153782183-3fd19213-b2dd-48b6-9a1c-24c736184a89.png)
Давай если значений нет, то не будем ничего показывать

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/156309485-5db9f00a-e57b-4018-9a67-446cd05ae4d2.png)
А зачем этот элемент? У него в свойствах стоит display: none.
![image](https://user-images.githubusercontent.com/89850975/156310244-0a957089-7aa1-4959-94e1-eaca9920bc0b.png)
На мобильной версии изображения комнат скрыты. Может стоит оставить и расположить их в ряд друг по другом. Прост так мы скрываем от пользователя главный контент это фото комнаты. Не лучшее решение

**Comment by gunzenroses** [comment]
> А зачем этот элемент? У него в свойствах стоит display: none.

Хотя элемента нет в макете, по ряду причин решила его добавить:
- оставлять раздел как **div** наверно было бы не вполне семантически лучшим решением, соответственно использован элемент **section**;
- в спецификации говорится, 'the theme of each section **should be identified**, typically **by including a heading** (h1–h6 element) as a child of the section element' (не обязательно, но опять же - лучше использовать);
- также добавление **header** в section улучшает доступность и помогает в работе вспомогательных технологий.
