### ISSUE TITLE
Миксины

### ISSUE THREAD

**Issue by osyka-yuri** [gunzenroses/hotelPage#9]
https://github.com/gunzenroses/hotelPage/blob/8f76abfb5d91ce3070c716f6eae277d5c419ccb7/src/assets/styles/media-mixins.scss#L7-L11
В таком виде миксины брейкпоинтов никакой пользы не несут, даже наоборот усложняют использование, так если нам нужно будет изменить значение какого брейкпоинта нам придется изменять и название миксина, что в последствии приведет к необходимости изменять это название во всем коде. Если и создавать миксины для брейкпоинтов, то нужно давать обобщенные имена, к примеру sm, md, lg и т.п. Это позволит изменять без каких-либо проблем размеры и при этом не нужно будет менять названия по всему сайту. И не нужно их так много делать, достаточно несколько штук под разные устройства. [Вот](https://getbootstrap.com/docs/5.0/layout/breakpoints/) для примера брейкпоинты из бутстрапа можно по аналогии сделать.

---

https://github.com/gunzenroses/hotelPage/blob/8f76abfb5d91ce3070c716f6eae277d5c419ccb7/src/assets/styles/mixins.scss#L1-L13
Здесь тоже достаточно тоже не совсем понятно какая польза от этого миксина. Да и в целом, как мне кажется, все миксины не совсем подходящие. Миксины нужно использовать тогда, когда там нужно переиспользовать какую-то логику, которая общая для всего сайта. К примеру, брейкпоинты или определение размеров текста и шрифтов. 

---

Так же почему файлы expand.scss и dropdown.scss находятся вне блоков?

**Comment by gunzenroses** [comment]
> Так же почему файлы expand.scss и dropdown.scss находятся вне блоков?

Это общие стили, я добавляю классы expand и dropdown в соответствующие компоненты, вместо того, чтобы каждый раз их заново определять (dry) :-)

**Comment by osyka-yuri** [comment]
> > Так же почему файлы expand.scss и dropdown.scss находятся вне блоков?
> 
> Это общие стили, я добавляю классы expand и dropdown в соответствующие компоненты, вместо того, чтобы каждый раз их заново определять (dry) :-)

В повторном определении стилей нечего плохого нет, блок должен быть максимально независым. В данном случае создается зависимость, и в случае изменения этих стилей скорее всего это окажет влияние на смежные блоки, и если будет цель изменить стили только одного блока, то уже нужно будет думать как это сделать не повлияв на все остальные, и уже этот блок так просто не перенесешь в другой проект к примеру, так как часть стилей находится отдельно.
https://github.com/gunzenroses/hotelPage/blob/8f76abfb5d91ce3070c716f6eae277d5c419ccb7/src/components/dropdown-guests/dropdown-guests.pug#L10-L12
Плюс ко всему создается несколько странная структура внутри блока dropdown находятся элементы которые ему не пренадлежат, такого быть не должно. 
Возможно dropdown должен быть одним блоком, а не разделен на два? Там ведь различие только в наличии кнопок, тогда и проблемы с повторением стилей не будет.

---

Почему миксин isFlex остался? Я не против него, но тут важно понимать какую пользу он несет, зависимость от каких-то вспомогательных средств зачастую усложняют поддержку проекта, так как другому разработчику нужно их знать чтобы с ними работать. К примеру в случае определения переменных для шрифтов/цветов значительно упрощает впоследствии их изменение, нам достаточно изменить эти значения в одном месте и их значения изменятся по всему сайту.  А в случае миксина мне не совсем понятна в чем польза, а вот недостатки он нарушает не зависимость блоков, так же если над проектом будет работать несколько разработчиков, то им необходимо знать о нем и правильно его применять.

**Comment by gunzenroses** [comment]
> Почему миксин isFlex остался?

- вместо написания шаблонных 4-5 строк можно передать несколько аргументов в одной;
- в некоторых случаях позволяет избежать повторное использование кода (при значениях по default) и ограничиться только названием миксина;
- поскольку общие миксины лежат в mixins.scss, это вроде как обеспечивает общий стиль приложения + помогает сохранять независимость компонентов.

Наличие миксина не принципиально, но вроде как ничего и не нарушает, при этом немного ускоряет верстку.

**Comment by osyka-yuri** [comment]
> > Почему миксин isFlex остался?
> 
> * вместо написания шаблонных 4-5 строк можно передать несколько аргументов в одной;
> * в некоторых случаях позволяет избежать повторное использование кода (при значениях по default) и ограничиться только названием миксина;
> * поскольку общие миксины лежат в mixins.scss, это вроде как обеспечивает общий стиль приложения + помогает сохранять независимость компонентов.
> 
> Наличие миксина не принципиально, но вроде как ничего и не нарушает, при этом немного ускоряет верстку.

Если действительно приносит пользу, то пусть остается)
